name: Setup Feedback
description: Share feedback or issues faced during CLI setup
title: "[Setup Feedback]: "

body:
  - type: textarea
    id: issue
    attributes:
      label: What issue did you face?
      placeholder: Briefly describe the problem during setup

  - type: textarea
    id: suggestion
    attributes:
      label: Any suggestion for improvement? (Optional)
      placeholder: What would make the setup better?