name: CLI Tool Request
description: Request addition of a new CLI tool to install.sh
title: "[Tool Request]: "

body:
  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      placeholder: e.g. terraform
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason (Optional)
      placeholder: Why do you need this tool?